"""empty message

Revision ID: 119062934ff5
Revises: 
Create Date: 2019-05-11 04:12:31.499295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '119062934ff5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engine_cost')
    op.drop_table('time_zone_leap_second')
    op.drop_table('role_edges')
    op.drop_table('time_zone_name')
    op.drop_table('time_zone_transition')
    op.drop_table('proxies_priv')
    op.drop_table('plugin')
    op.drop_table('slow_log')
    op.drop_table('slave_master_info')
    op.drop_index('name', table_name='help_category')
    op.drop_table('help_category')
    op.drop_table('innodb_index_stats')
    op.drop_table('innodb_table_stats')
    op.drop_table('db')
    op.drop_table('tables_priv')
    op.drop_table('component')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Reload_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Shutdown_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Process_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('File_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_db_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Super_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_slave_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_client_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_user_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tablespace_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('ssl_type', mysql.ENUM('', 'ANY', 'X509', 'SPECIFIED', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("''"), nullable=False),
    sa.Column('ssl_cipher', sa.BLOB(), nullable=False),
    sa.Column('x509_issuer', sa.BLOB(), nullable=False),
    sa.Column('x509_subject', sa.BLOB(), nullable=False),
    sa.Column('max_questions', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_updates', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_user_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('plugin', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("'caching_sha2_password'"), nullable=False),
    sa.Column('authentication_string', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('password_expired', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('password_last_changed', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password_lifetime', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('account_locked', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_role_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_role_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Password_reuse_history', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Password_reuse_time', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Password_require_current', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), nullable=True),
    sa.Column('User_attributes', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('Host', 'User'),
    mysql_collate='utf8_bin',
    mysql_comment='Users and global privileges',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('component',
    sa.Column('component_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('component_group_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('component_urn', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('component_id'),
    mysql_comment='Components',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tables_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=93), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Table_priv', mysql.SET(charset='utf8', collation='utf8_general_ci', length=11), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_priv', mysql.SET(charset='utf8', collation='utf8_general_ci', length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Table_name'),
    mysql_collate='utf8_bin',
    mysql_comment='Table privileges',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('db',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User'),
    mysql_collate='utf8_bin',
    mysql_comment='Database privileges',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('innodb_table_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8_bin', length=199), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('n_rows', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('clustered_index_size', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sum_of_other_index_sizes', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('innodb_index_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8_bin', length=199), nullable=False),
    sa.Column('index_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('stat_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('stat_value', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sample_size', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('stat_description', mysql.VARCHAR(collation='utf8_bin', length=1024), nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name', 'index_name', 'stat_name'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('help_category',
    sa.Column('help_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('parent_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_category_id'),
    mysql_comment='help categories',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'help_category', ['name'], unique=True)
    op.create_table('slave_master_info',
    sa.Column('Number_of_lines', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Master_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Master_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Host', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), nullable=True),
    sa.Column('User_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('User_password', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Port', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Connect_retry', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Enabled_ssl', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Ssl_ca', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_capath', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_cert', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_cipher', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_key', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_verify_server_cert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Heartbeat', mysql.FLOAT(), nullable=False),
    sa.Column('Bind', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ignored_server_ids', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Uuid', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Retry_count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Ssl_crl', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_crlpath', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Enabled_auto_position', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Channel_name', mysql.CHAR(charset='utf8', collation='utf8_general_ci', length=64), nullable=False),
    sa.Column('Tls_version', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Public_key_path', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Get_public_key', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Network_namespace', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.PrimaryKeyConstraint('Channel_name'),
    mysql_comment='Master Information',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('slow_log',
    sa.Column('start_time', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('query_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('lock_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('rows_sent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rows_examined', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('db', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('last_insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sql_text', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('thread_id', mysql.BIGINT(display_width=21, unsigned=True), autoincrement=False, nullable=False),
    mysql_comment='Slow log',
    mysql_default_charset='utf8',
    mysql_engine='CSV'
    )
    op.create_table('plugin',
    sa.Column('name', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('dl', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_comment='MySQL plugins',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('proxies_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_user', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('With_grant', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=93), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Proxied_host', 'Proxied_user'),
    mysql_collate='utf8_bin',
    mysql_comment='User proxy privileges',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_transition',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_time'),
    mysql_comment='Time zone transitions',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_name',
    sa.Column('Name', mysql.CHAR(length=64), nullable=False),
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Name'),
    mysql_comment='Time zone names',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('role_edges',
    sa.Column('FROM_HOST', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('FROM_USER', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('TO_HOST', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('TO_USER', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('WITH_ADMIN_OPTION', mysql.ENUM('N', 'Y', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('FROM_HOST', 'FROM_USER', 'TO_HOST', 'TO_USER'),
    mysql_collate='utf8_bin',
    mysql_comment='Role hierarchy and role grants',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_leap_second',
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Correction', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Transition_time'),
    mysql_comment='Leap seconds information for time zones',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('engine_cost',
    sa.Column('engine_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('device_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cost_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('cost_value', mysql.FLOAT(), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('default_value', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('cost_name', 'engine_name', 'device_type'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
