"""first version

Revision ID: 3ce845f59496
Revises: 
Create Date: 2019-04-09 18:16:26.779586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce845f59496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints_final',
    sa.Column('end_id', sa.Integer(), nullable=False),
    sa.Column('svc_id', sa.Integer(), nullable=True),
    sa.Column('end_name', sa.String(length=400), nullable=False),
    sa.Column('end_url', sa.String(length=400), nullable=False),
    sa.Column('end_description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('end_id'),
    sa.UniqueConstraint('end_url'),
    sa.UniqueConstraint('svc_id')
    )
    op.create_index(op.f('ix_endpoints_final_end_name'), 'endpoints_final', ['end_name'], unique=True)
    op.create_table('endpoints_temp',
    sa.Column('svc_name', sa.String(length=400), nullable=False),
    sa.Column('end_name', sa.String(length=400), nullable=False),
    sa.Column('end_url', sa.String(length=400), nullable=False),
    sa.Column('end_description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('end_name'),
    sa.UniqueConstraint('end_url')
    )
    op.create_index(op.f('ix_endpoints_temp_end_name'), 'endpoints_temp', ['end_name'], unique=True)
    op.create_index(op.f('ix_endpoints_temp_svc_name'), 'endpoints_temp', ['svc_name'], unique=True)
    op.create_table('services_final',
    sa.Column('svc_id', sa.Integer(), nullable=False),
    sa.Column('svc_name', sa.String(length=400), nullable=False),
    sa.Column('svc_entrypoint', sa.String(length=400), nullable=False),
    sa.Column('svc_description', sa.String(length=4000), nullable=True),
    sa.Column('svc_endpoints', sa.Integer(), nullable=False),
    sa.Column('svc_status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('svc_id'),
    sa.UniqueConstraint('svc_entrypoint')
    )
    op.create_index(op.f('ix_services_final_svc_endpoints'), 'services_final', ['svc_endpoints'], unique=False)
    op.create_index(op.f('ix_services_final_svc_name'), 'services_final', ['svc_name'], unique=True)
    op.create_index(op.f('ix_services_final_svc_status'), 'services_final', ['svc_status'], unique=False)
    op.create_table('services_temp',
    sa.Column('svc_name', sa.String(length=400), nullable=False),
    sa.Column('svc_entrypoint', sa.String(length=400), nullable=False),
    sa.Column('svc_description', sa.String(length=4000), nullable=True),
    sa.Column('svc_endpoints', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('svc_name'),
    sa.UniqueConstraint('svc_entrypoint')
    )
    op.create_index(op.f('ix_services_temp_svc_endpoints'), 'services_temp', ['svc_endpoints'], unique=False)
    op.create_index(op.f('ix_services_temp_svc_name'), 'services_temp', ['svc_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_temp_svc_name'), table_name='services_temp')
    op.drop_index(op.f('ix_services_temp_svc_endpoints'), table_name='services_temp')
    op.drop_table('services_temp')
    op.drop_index(op.f('ix_services_final_svc_status'), table_name='services_final')
    op.drop_index(op.f('ix_services_final_svc_name'), table_name='services_final')
    op.drop_index(op.f('ix_services_final_svc_endpoints'), table_name='services_final')
    op.drop_table('services_final')
    op.drop_index(op.f('ix_endpoints_temp_svc_name'), table_name='endpoints_temp')
    op.drop_index(op.f('ix_endpoints_temp_end_name'), table_name='endpoints_temp')
    op.drop_table('endpoints_temp')
    op.drop_index(op.f('ix_endpoints_final_end_name'), table_name='endpoints_final')
    op.drop_table('endpoints_final')
    # ### end Alembic commands ###
