"""'mysql1'

Revision ID: 3e8d1a0e9ae9
Revises: 
Create Date: 2019-05-14 22:10:27.446596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8d1a0e9ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints_temp',
    sa.Column('svc_name', sa.String(length=500), nullable=True),
    sa.Column('end_name', sa.String(length=500), nullable=True),
    sa.Column('end_url', sa.String(length=500), nullable=False),
    sa.Column('end_description', sa.String(length=9999), nullable=True),
    sa.PrimaryKeyConstraint('end_url')
    )
    op.create_table('services_final',
    sa.Column('svc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('svc_name', sa.String(length=500), nullable=True),
    sa.Column('svc_entrypoint', sa.String(length=500), nullable=False),
    sa.Column('svc_description', sa.String(length=9999), nullable=True),
    sa.Column('svc_endpoints', sa.Integer(), nullable=True),
    sa.Column('svc_status', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('svc_id', 'svc_entrypoint')
    )
    op.create_table('services_temp',
    sa.Column('tsvc_name', sa.String(length=500), nullable=True),
    sa.Column('tsvc_entrypoint', sa.String(length=500), nullable=False),
    sa.Column('tsvc_description', sa.String(length=9999), nullable=True),
    sa.Column('tsvc_endpoints', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tsvc_entrypoint')
    )
    op.create_table('endpoints_final',
    sa.Column('end_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('svc_id', sa.Integer(), nullable=True),
    sa.Column('end_name', sa.String(length=500), nullable=True),
    sa.Column('end_url', sa.String(length=500), nullable=False),
    sa.Column('end_description', sa.String(length=9999), nullable=True),
    sa.ForeignKeyConstraint(['svc_id'], ['services_final.svc_id'], ),
    sa.PrimaryKeyConstraint('end_id', 'end_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endpoints_final')
    op.drop_table('services_temp')
    op.drop_table('services_final')
    op.drop_table('endpoints_temp')
    # ### end Alembic commands ###
