"""empty message

Revision ID: 4d7ce3129e56
Revises: 
Create Date: 2019-04-15 08:51:33.562727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7ce3129e56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints_final',
    sa.Column('end_id', sa.Integer(), nullable=False),
    sa.Column('svc_id', sa.Integer(), nullable=True),
    sa.Column('end_name', sa.String(length=400), nullable=False),
    sa.Column('end_url', sa.String(length=400), nullable=False),
    sa.Column('end_description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('end_id'),
    sa.UniqueConstraint('end_url'),
    sa.UniqueConstraint('svc_id')
    )
    op.create_index(op.f('ix_endpoints_final_end_name'), 'endpoints_final', ['end_name'], unique=False)
    op.create_table('endpoints_temp',
    sa.Column('tsvc_name', sa.String(length=400), nullable=False),
    sa.Column('tend_name', sa.String(length=400), nullable=True),
    sa.Column('tend_url', sa.String(length=400), nullable=False),
    sa.Column('tend_description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('tend_url')
    )
    op.create_index(op.f('ix_endpoints_temp_tend_name'), 'endpoints_temp', ['tend_name'], unique=False)
    op.create_index(op.f('ix_endpoints_temp_tsvc_name'), 'endpoints_temp', ['tsvc_name'], unique=False)
    op.create_table('services_final',
    sa.Column('svc_id', sa.Integer(), nullable=False),
    sa.Column('svc_name', sa.String(length=400), nullable=False),
    sa.Column('svc_entrypoint', sa.String(length=400), nullable=False),
    sa.Column('svc_description', sa.String(length=4000), nullable=True),
    sa.Column('svc_endpoints', sa.Integer(), nullable=False),
    sa.Column('svc_status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('svc_id'),
    sa.UniqueConstraint('svc_entrypoint')
    )
    op.create_index(op.f('ix_services_final_svc_endpoints'), 'services_final', ['svc_endpoints'], unique=False)
    op.create_index(op.f('ix_services_final_svc_name'), 'services_final', ['svc_name'], unique=False)
    op.create_index(op.f('ix_services_final_svc_status'), 'services_final', ['svc_status'], unique=False)
    op.create_table('services_temp',
    sa.Column('tsvc_name', sa.String(length=400), nullable=False),
    sa.Column('tsvc_entrypoint', sa.String(length=400), nullable=False),
    sa.Column('tsvc_description', sa.String(length=4000), nullable=True),
    sa.Column('tsvc_endpoints', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tsvc_entrypoint')
    )
    op.create_index(op.f('ix_services_temp_tsvc_endpoints'), 'services_temp', ['tsvc_endpoints'], unique=False)
    op.create_index(op.f('ix_services_temp_tsvc_name'), 'services_temp', ['tsvc_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_temp_tsvc_name'), table_name='services_temp')
    op.drop_index(op.f('ix_services_temp_tsvc_endpoints'), table_name='services_temp')
    op.drop_table('services_temp')
    op.drop_index(op.f('ix_services_final_svc_status'), table_name='services_final')
    op.drop_index(op.f('ix_services_final_svc_name'), table_name='services_final')
    op.drop_index(op.f('ix_services_final_svc_endpoints'), table_name='services_final')
    op.drop_table('services_final')
    op.drop_index(op.f('ix_endpoints_temp_tsvc_name'), table_name='endpoints_temp')
    op.drop_index(op.f('ix_endpoints_temp_tend_name'), table_name='endpoints_temp')
    op.drop_table('endpoints_temp')
    op.drop_index(op.f('ix_endpoints_final_end_name'), table_name='endpoints_final')
    op.drop_table('endpoints_final')
    # ### end Alembic commands ###
