"""'sqlite'

Revision ID: 827dbda76ea4
Revises: 
Create Date: 2019-05-24 02:20:58.673313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827dbda76ea4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints_final',
    sa.Column('end_id', sa.Integer(), nullable=False),
    sa.Column('svc_id', sa.Integer(), nullable=True),
    sa.Column('end_name', sa.String(length=500), nullable=True),
    sa.Column('end_url', sa.String(length=500), nullable=False),
    sa.Column('end_description', sa.String(length=9999), nullable=True),
    sa.PrimaryKeyConstraint('end_id', 'end_url')
    )
    op.create_table('endpoints_temp',
    sa.Column('svc_name', sa.String(length=500), nullable=True),
    sa.Column('end_name', sa.String(length=500), nullable=True),
    sa.Column('end_url', sa.String(length=500), nullable=False),
    sa.Column('end_description', sa.String(length=9999), nullable=True),
    sa.PrimaryKeyConstraint('end_url')
    )
    op.create_table('services_final',
    sa.Column('svc_id', sa.Integer(), nullable=False),
    sa.Column('svc_name', sa.String(length=500), nullable=True),
    sa.Column('svc_entrypoint', sa.String(length=500), nullable=False),
    sa.Column('svc_description', sa.String(length=9999), nullable=True),
    sa.Column('svc_endpoints', sa.Integer(), nullable=True),
    sa.Column('svc_status', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('svc_id', 'svc_entrypoint'),
    sa.UniqueConstraint('svc_entrypoint'),
    sa.UniqueConstraint('svc_id')
    )
    op.create_table('services_temp',
    sa.Column('tsvc_name', sa.String(length=500), nullable=True),
    sa.Column('tsvc_entrypoint', sa.String(length=500), nullable=False),
    sa.Column('tsvc_description', sa.String(length=9999), nullable=True),
    sa.Column('tsvc_endpoints', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tsvc_entrypoint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_temp')
    op.drop_table('services_final')
    op.drop_table('endpoints_temp')
    op.drop_table('endpoints_final')
    # ### end Alembic commands ###
